services:
  reddit-keywords-discord-notifier:
    container_name: skdn
    image: skdn
    restart: always
    environment:
      - DISCORD_TOKEN=yourtoken
      - CHANNEL_ID=yourid
      - REDDIT_CLIENT_ID=yourid
      - REDDIT_CLIENT_SECRET=yoursecret
      - REDDIT_USER_AGENT="User-Agent:subreddit keyword scanner by u/your_username"
      - MONITOR_SUB="subreddit" # no r/, just the name
      - KEYWORDS="list,of,keywords"
      - ENABLE_WELCOME_MESSAGE=true # sends a monitoring description to Discord on start
      - NEW_POST_LIMIT=10 # specifies the # of new posts that are scanned per check
      - CHECK_FREQUENCY=60 # controls how often the script checks your subreddit
